# Generated by Django 4.2.15 on 2024-09-19 11:24

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_production_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settingUp',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
