# Generated by Django 4.2.15 on 2024-09-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_settingup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='settingUp',
        ),
    ]
