# Generated by Django 4.2.15 on 2025-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userdepposition_remove_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='QR-код для входа'),
        ),
    ]
