# Generated by Django 4.2.15 on 2025-09-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_name', models.CharField(max_length=250, verbose_name='Наименование рабочего места')),
                ('type_of_equipment', models.CharField(max_length=250, verbose_name='Наименование оборудования')),
                ('inv_number', models.IntegerField(verbose_name='Инвентарный номер оборудования')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='production_area_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.workplace'),
        ),
    ]
