# Generated by Django 4.2.15 on 2026-03-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_workplace_alter_user_production_area_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_area_name', models.CharField(max_length=150, verbose_name='Наименование производственного участка')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='production_area_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.productionarea'),
        ),
    ]
