# Generated by Django 4.2.15 on 2026-03-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_user_production_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='production_area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.productionarea'),
        ),
    ]
