# Generated by Django 5.1 on 2024-08-14 04:20

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('page_access', models.CharField(verbose_name='Страницы')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Task_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_name', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_name', models.CharField(max_length=250, verbose_name='Наименование рабочего места')),
                ('type_of_equipment', models.CharField(max_length=250, verbose_name='Наименование оборудования')),
                ('inv_number', models.IntegerField(verbose_name='Инвентарный номер оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('position_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.access_app')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('user_family', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('user_second_name', models.CharField(max_length=250, verbose_name='Отчество')),
                ('user_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.positions')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('task_timedate_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('task_timedate_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('task_profile_amount', models.BigIntegerField(verbose_name='Количество')),
                ('task_comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('task_timedate_start_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время начала')),
                ('task_timedate_end_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время окончания')),
                ('task_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.task_history')),
                ('task_profile_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.profile_type')),
                ('task_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.task_status')),
                ('task_user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.users')),
                ('task_workplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.workplace')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
