# Generated by Django 5.1 on 2024-08-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_tasks_task_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_user_created',
            field=models.CharField(default='Неизвестный пользователь', max_length=250, verbose_name='Кто создал задачу'),
        ),
    ]
