# Generated by Django 5.1 on 2024-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_tasks_task_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTypeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_problem', models.CharField(max_length=100, verbose_name='Наименование типа проблемы')),
            ],
        ),
    ]
