# Generated by Django 5.1 on 2024-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_mastertypeproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_is_vision',
            field=models.BooleanField(default=True, verbose_name='Видимость задачи'),
        ),
    ]
