# Generated by Django 4.2.15 on 2024-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_tasks_task_time_settingup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_time_settingUp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время начала наладки'),
        ),
    ]
