# Generated by Django 4.2.15 on 2024-09-19 12:56

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_tasks_task_time_settingup'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='settingUp',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
