# Generated by Django 4.2.15 on 2024-09-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_users_settingup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
