# Generated by Django 4.2.15 on 2024-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='profile_amount_now',
            field=models.BigIntegerField(default=0, verbose_name='Количество профиля текущего'),
        ),
    ]
