# Generated by Django 4.2.15 on 2024-10-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_tasks_profile_amount_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_profile_length',
            field=models.BigIntegerField(default=0, verbose_name='Длина профиля'),
        ),
    ]
