# Generated by Django 4.2.15 on 2024-10-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_tasks_task_profile_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_profile_length',
            field=models.FloatField(default=0, verbose_name='Длина профиля'),
        ),
    ]
