# Generated by Django 5.1.3 on 2024-12-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_tasks_worker_accepted_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_time_settingUp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время начала наладки'),
        ),
    ]
