# Generated by Django 4.2.15 on 2025-07-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_alter_tasks_task_time_settingup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_comments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
    ]
