# Generated by Django 4.2.15 on 2025-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_alter_tasks_task_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profile', models.CharField(max_length=50, verbose_name='Общий тип профиля')),
                ('names_profile', models.TextField(blank=True, default='', null=True, verbose_name='Входящие тип профиля')),
            ],
        ),
    ]
