# Generated by Django 4.2.15 on 2025-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_acceptedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_type',
            name='association_name',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Общее название'),
        ),
    ]
