# Generated by Django 4.2.15 on 2025-08-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_profile_type_association_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedprofile',
            name='names_profile',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Входящий тип профиля'),
        ),
    ]
