# Generated by Django 4.2.15 on 2025-08-10 14:00

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_profile_type_association_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('page_access', models.CharField(max_length=500, verbose_name='Страницы')),
            ],
            options={
                'verbose_name': 'Доступ к приложению',
                'verbose_name_plural': 'Доступы к приложению',
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('association_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Общее название')),
            ],
            options={
                'verbose_name': 'Тип профиля',
                'verbose_name_plural': 'Типы профилей',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_name', django.contrib.postgres.fields.hstore.HStoreField(verbose_name='История')),
            ],
            options={
                'verbose_name': 'История задачи',
                'verbose_name_plural': 'История задач',
            },
        ),
        migrations.RenameModel(
            old_name='Task_status',
            new_name='TaskStatus',
        ),
        migrations.AlterModelOptions(
            name='acceptedprofile',
            options={'verbose_name': 'Принятый профиль', 'verbose_name_plural': 'Принятые профили'},
        ),
        migrations.AlterModelOptions(
            name='mastertypeproblem',
            options={'verbose_name': 'Тип проблемы', 'verbose_name_plural': 'Типы проблем'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name': 'Статус задачи', 'verbose_name_plural': 'Статусы задач'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.AlterField(
            model_name='acceptedprofile',
            name='names_profile',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Входящий тип профиля'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.taskstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.workplace', verbose_name='Рабочее место'),
        ),
        migrations.RunSQL(
            "INSERT INTO master_accessapp (id, access_name, page_access) SELECT id, access_name, page_access FROM master_access_app;",
            reverse_sql="DELETE FROM master_accessapp;"
        ),
        migrations.RunSQL(
            "INSERT INTO master_profiletype (id, profile_name, association_name) SELECT id, profile_name, association_name FROM master_profile_type;",
            reverse_sql="DELETE FROM master_profiletype;"
        ),
        migrations.RunSQL(
            "INSERT INTO master_taskhistory (id, history_name) SELECT id, history_name FROM master_task_history;",
            reverse_sql="DELETE FROM master_taskhistory;"
        ),
        migrations.AlterField(
            model_name='positions',
            name='position_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.accessapp', verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.taskhistory', verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_profile_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.profiletype', verbose_name='Тип профиля'),
        ),
        migrations.DeleteModel(
            name='Access_app',
        ),
        migrations.DeleteModel(
            name='Profile_type',
        ),
        migrations.DeleteModel(
            name='Task_history',
        ),
    ]
