# Generated by Django 4.2.15 on 2025-08-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_accessapp_profiletype_taskhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='is_accepted_video',
            field=models.BooleanField(default=False, null=True, verbose_name='Доступно для видео?'),
        ),
    ]
