# Generated by Django 4.2.15 on 2025-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_profiletype_is_accepted_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='yolo_model_name',
            field=models.CharField(blank=True, default='', verbose_name='Название модели нейросети'),
        ),
    ]
