# Generated by Django 4.2.15 on 2025-08-23 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_profiletype_yolo_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShtripsValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_offs_shtrips', models.CharField(verbose_name='Тип списания (кг или метры)')),
            ],
        ),
        migrations.RemoveField(
            model_name='profiletype',
            name='association_name',
        ),
        migrations.AddField(
            model_name='profiletype',
            name='association_name_shtrips',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Тип штрипса'),
        ),
        migrations.CreateModel(
            name='OffsShtrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 8, 23, 6, 34, 55, 956843), verbose_name='Фактическая дата и время списания')),
                ('type_value_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.shtripsvaluetype')),
            ],
            options={
                'verbose_name': 'История списания',
                'verbose_name_plural': 'Истории списаний',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='history_offs_shtrips',
            field=models.ManyToManyField(to='master.offsshtrips'),
        ),
    ]
