# Generated by Django 4.2.15 on 2025-08-23 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_shtripsvaluetype_remove_profiletype_association_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsshtrips',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Фактическая дата и время списания'),
        ),
    ]
