# Generated by Django 4.2.15 on 2025-09-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_alter_offsshtrips_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', verbose_name='Наименование')),
                ('width_steel', models.IntegerField(blank=True, verbose_name='Толщина стали')),
            ],
        ),
        migrations.CreateModel(
            name='SteelTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, verbose_name='вес профиля (кг/пог.м)')),
                ('type_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.profiletype', verbose_name='Тип профиля')),
                ('type_steel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.steeltype', verbose_name='Тип стали')),
            ],
        ),
    ]
