# Generated by Django 4.2.15 on 2025-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_steeltype_steeltypeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steeltype',
            name='width_steel',
            field=models.FloatField(blank=True, verbose_name='Толщина стали'),
        ),
    ]
