# Generated by Django 4.2.15 on 2025-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_alter_steeltype_width_steel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='paint_consumption',
            field=models.FloatField(blank=True, default=0, verbose_name='Расход краски'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiletype',
            name='quantity_per_package',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество в упаковке'),
            preserve_default=False,
        ),
    ]
