# Generated by Django 4.2.15 on 2025-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_profiletype_paint_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='paint_consumption',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Расход краски'),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='quantity_per_package',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество в упаковке'),
        ),
    ]
