# Generated by Django 4.2.15 on 2025-09-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_alter_profiletype_paint_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_profile_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.steeltype', verbose_name='Тип материала'),
        ),
    ]
