# Generated by Django 4.2.15 on 2025-09-04 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_workplace_alter_user_production_area_id'),
        ('master', '0027_tasks_task_profile_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Фактическая дата и время списания')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип события')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет в формате #456456')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profiletype',
            options={'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.workplace', verbose_name='Рабочее место'),
        ),
        migrations.DeleteModel(
            name='Workplace',
        ),
        migrations.AddField(
            model_name='historyevent',
            name='type_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.typeevent'),
        ),
        migrations.AddField(
            model_name='historyevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='history_event_messages',
            field=models.ManyToManyField(to='master.historyevent'),
        ),
    ]
