# Generated by Django 4.2.15 on 2025-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_historyevent_typeevent_alter_profiletype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyevent',
            name='message',
            field=models.CharField(max_length=500, verbose_name='Сообщение'),
        ),
    ]
