# Generated by Django 4.2.15 on 2025-09-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_alter_historyevent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_history',
        ),
    ]
