# Generated by Django 4.2.15 on 2025-09-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0030_remove_tasks_task_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProfileRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество изготовленного профиля')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Фактическая дата и время списания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='history_profile_records',
            field=models.ManyToManyField(to='master.historyprofilerecords'),
        ),
    ]
