# Generated by Django 4.2.15 on 2025-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0031_historyprofilerecords_tasks_history_profile_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение количества профиля в задаче'),
        ),
    ]
