# Generated by Django 4.2.15 on 2025-09-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0032_tasks_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiletype',
            options={'verbose_name': 'Тип профиля', 'verbose_name_plural': 'Типы профилей'},
        ),
    ]
