# Generated by Django 4.2.15 on 2025-09-04 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0033_alter_profiletype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyprofilerecords',
            name='profile_sum',
            field=models.IntegerField(default=0, verbose_name='Всего профиля на данный момент'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания задачи'),
        ),
    ]
