# Generated by Django 4.2.15 on 2025-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_historyprofilerecords_profile_sum_tasks_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyprofilerecords',
            options={'get_latest_by': 'id'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='sensor_true',
            field=models.BooleanField(default=False),
        ),
    ]
