# Generated by Django 4.2.15 on 2026-03-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_user_production_area_id'),
        ('master', '0035_alter_historyprofilerecords_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='production_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.productionarea', verbose_name='Производственный участок'),
        ),
    ]
