# Generated by Django 4.2.15 on 2026-03-17 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_task_creator_to_fk(apps, schema_editor):
    Task = apps.get_model('master', 'Tasks')
    User = apps.get_model('login', 'User')

    name_to_user_ids = {}
    username_to_user_ids = {}

    for user in User.objects.all().only('id', 'first_name', 'last_name', 'username'):
        full_name = f'{(user.last_name or "").strip()} {(user.first_name or "").strip()}'.strip()
        if full_name:
            name_to_user_ids.setdefault(full_name, []).append(user.id)
        if user.username:
            username_to_user_ids.setdefault(user.username.strip(), []).append(user.id)

    for task in Task.objects.filter(task_user_created_by__isnull=True).only('id', 'task_user_created'):
        raw_value = (task.task_user_created or '').strip()
        matched_user_id = None

        full_name_matches = name_to_user_ids.get(raw_value, [])
        if len(full_name_matches) == 1:
            matched_user_id = full_name_matches[0]
        else:
            username_matches = username_to_user_ids.get(raw_value, [])
            if len(username_matches) == 1:
                matched_user_id = username_matches[0]

        if matched_user_id is not None:
            Task.objects.filter(id=task.id).update(task_user_created_by_id=matched_user_id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0036_tasks_production_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_user_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
        migrations.RunPython(copy_task_creator_to_fk, migrations.RunPython.noop),
    ]
