# Generated by Django 4.2.15 on 2026-05-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0037_tasks_task_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип покрытия')),
            ],
            options={
                'verbose_name': 'Тип покрытия',
                'verbose_name_plural': 'Типы покрытия',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_coating_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь покрытия'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_profile_length',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Длина профиля'),
        ),
        migrations.CreateModel(
            name='CoatingThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Толщина покрытия')),
                ('coating_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thicknesses', to='master.coatingtype', verbose_name='Тип покрытия')),
            ],
            options={
                'verbose_name': 'Толщина покрытия',
                'verbose_name_plural': 'Толщины покрытия',
                'ordering': ('coating_type__name', 'value'),
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_coating_thickness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.coatingthickness', verbose_name='Толщина покрытия'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_coating_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.coatingtype', verbose_name='Тип покрытия'),
        ),
    ]
