# Generated by Django 4.2.15 on 2026-05-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0038_coatingtype_tasks_task_coating_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_coating_thickness',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Толщина покрытия'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_profile_material',
            field=models.FloatField(blank=True, null=True, verbose_name='Толщина материала'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE master_tasks AS task
                SET task_coating_thickness = coating.value::text
                FROM master_coatingthickness AS coating
                WHERE task.task_coating_thickness ~ '^[0-9]+$'
                  AND task.task_coating_thickness::bigint = coating.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                UPDATE master_tasks AS task
                SET task_profile_material = steel.width_steel
                FROM master_steeltype AS steel
                WHERE task.task_profile_material = steel.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
