# Generated by Django 4.2.15 on 2026-05-27 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0039_alter_tasks_task_coating_thickness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProfileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество изготовленного профиля')),
                ('profile_sum', models.IntegerField(default=0, verbose_name='Всего профиля на данный момент')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_records', to='master.tasks')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись по профилю',
                'verbose_name_plural': 'Записи по профилю',
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='master.tasks')),
                ('type_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.typeevent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие задачи',
                'verbose_name_plural': 'События задач',
            },
        ),
        migrations.CreateModel(
            name='WorkerAnalyticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('setting_up_hours', models.FloatField(default=0.0, verbose_name='Часы на переналадку')),
                ('profile_amount', models.IntegerField(default=0, verbose_name='Количество профиля')),
                ('work_time_hours', models.FloatField(default=0.0, verbose_name='Время работы (ч)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.tasks')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аналитическая запись пользователя',
                'verbose_name_plural': 'Аналитические записи пользователей',
                'unique_together': {('user', 'task', 'month', 'year')},
            },
        ),
    ]
