# Generated by Django 4.2.15 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0040_taskprofilerecord_taskevent_workeranalyticsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_order_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер заказа'),
        ),
    ]
