# Generated by Django 4.2.15 on 2026-09-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0042_tasks_planned_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyprofilerecords',
            name='coating_thickness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Базовое покрытие при изготовлении'),
        ),
        migrations.AddField(
            model_name='offsshtrips',
            name='coating_thickness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Базовое покрытие при установке'),
        ),
        migrations.AddField(
            model_name='taskprofilerecord',
            name='coating_thickness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Базовое покрытие при изготовлении'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='allow_stock',
            field=models.BooleanField(default=False, verbose_name='Разрешить изготовление на склад'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='coating_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='coating_start_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='stock_decision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Решение о доработке на склад'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='stock_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_task', to='master.tasks', verbose_name='Исходное задание'),
        ),
    ]
