# Generated by Django 4.2.15 on 2024-09-19 13:13

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingUp', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Количество времени на переналадку')),
                ('profile_amount', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Количество изготовленного профиля по датам')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
