# Generated by Django 4.2.15 on 2024-09-21 12:15

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_users_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_analytics',
            name='work_time',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Время полезной работы'),
        ),
    ]
