# Generated by Django 4.2.15 on 2025-09-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_users_analytics_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertypeproblem',
            name='name_problem',
            field=models.CharField(max_length=500, verbose_name='Наименование типа проблемы'),
        ),
    ]
